### ISSUE TITLE
Report to define set of species to feed into Pantheon analysis

### ISSUE THREAD

**Issue by DavidRoy** [BiologicalRecordsCentre/Pantheon#11] opened 2016-03-11 15:39 UTC
The ability to flexibly group data across samples/surveys etc (e.g. Defining a list from separate pit-fall trapping runs, or a combined list across multiple years for the same site). 

An extension of the current report filtering system used in iRecord?

**Comment by johnvanbreda** [comment] 2016-03-17 21:12
Can this requirement be met by the current filtering system? Or do you need to be able to pick an arbitrary list of samples not separable by other means. For example, if I run 3 pitfall traps on consecutive nights, the current system would not allow me to analyse just the first and third nights.

**Comment by DavidRoy** [comment] 2016-03-18 16:25
Perhaps start with the current filtering, but what would be the development effort to:
1. In the standard explore reports, provide a tab to list samples
2. Extend the filtering to allow a set of samples be defined (perhaps by ID?)

**Comment by johnvanbreda** [comment] 2016-05-16 19:38
Allowing the reports to be run against arbitrary lists of records/samples in the first place - ballpark 3-5 days. 
Add a tab to list samples: 2 hours estimate
Allow a list of samples to be picked and fed into the reports (by ID): ballpark 1-2 days (as needs a bit of UI thought).

**Comment by johnvanbreda** [comment] 2018-01-16 14:36
Duplicate of #33

**Closed as completed by johnvanbreda** 2018-01-16 14:36 UTC
Labels: enhancement, reports, high priority
