### ISSUE TITLE
Changes to OSIRIS reporting output

### ISSUE THREAD

**Issue by johnvanbreda** [BiologicalRecordsCentre/Pantheon#42] opened 2016-05-17 12:09 UTC
1) Refer to Jon's Word document
2) OSIRIS top level (ecological divisions). Add a fake super category to show resources plant associated, other and dung & carrion as an extra heading (alongside the ecological divisions). Heading is dung, carrion, and flowers.
When you click on this you can then see the 3 resources as the next level. They are effectively 3 orphan resources with a fake parent.

**Comment by johnvanbreda** [comment] 2016-05-17 12:13
Data structure (no code change) - the 3 tree associated divisions (arboreal, decaying wood/saproxylic, shaded woodland floor) should actually be habitats under the single Tree associated resource.

**Comment by johnvanbreda** [comment] 2016-05-17 12:44
New tabular format output for the OSIRIS hierarchy. A grid of all the resources in the analysis. Columns:
broad biotope
number of sp.
% representation (number in the sample vs total for that broad biotope in full Pantheon dataset)
specific habitat + same number & % column
resource + same number & % column

This lets you see a single resource plus it's parents in a single row and sort by anything.
For resources with parents, show the parents as individual rows as well as the hierarchies with chevrons, e..g
stuff
stuff >> more stuff

**Comment by johnvanbreda** [comment] 2016-05-17 12:45
Potential alternative is just to add the % representation to the hierarchical view we already have.

**Comment by johnvanbreda** [comment] 2016-05-17 12:51
One more output for OSIRIS. An alternative view of the important resources, broken down into some arbitrary categories defined in Jon's document. E.g. Grouped riparian traits. these groupings will be hard coded, not loaded from the DB. 
User gets a checkbox list of the different "categories" and can tick off the ones to include. Then for each they get a table output with the resource, # of sp. and % representation. Hierarchy of resources shown nested on separated lines.

**Comment by HDean** [comment] 2016-05-18 15:24
Linked to #15

**Comment by johnvanbreda** [comment] 2016-09-20 14:37
The layout described above for the tabular output is almost identical to the tabular output developed for #15 except the rows here are locked together (i.e. a resource always appears in the same row as it's specific and broad biotope). In the other format, colours are used to tie the resource and specific biotopes to their broad biotopes.

**Comment by johnvanbreda** [comment] 2016-10-03 12:21
@andrewvanbreda Please can you let me know what the names of the top level broad biotopes are in the updated database. In the copy currently loaded I can see one for dung & carrion but not plant associated or other (see the top comment). Not sure if this is still relevant to the current data.

**Comment by andrewvanbreda** [comment] 2016-10-03 12:24
wetland
open habitats  
coastal 
dung & carrion  
tree-associated

**Comment by HDean** [comment] 2016-10-03 12:37
@andrewvanbreda 
Is there not one for P1 plant-associated?
(technically dung and carrion and plant associated are not broad biotopes but for the purposes of reporting they are used in the same way as broad biotopes)

**Comment by andrewvanbreda** [comment] 2016-10-03 13:03
P1 plant-associated is held in a separate termlist, not as part of the broad biotopes/specific biotopes/resources list

Looking at the import data in the import files (which are taken straight from the database), the importer on my machine has behaved as intended as the plant-associated item does not have a type of "broad biotope" listed against it, it has no type. Also the items under it such as "inflorescence-associated" have no type.
So the system has created their own list.

Having said that, just because the system has behaved as intended, doesn't mean that it is what you want. I suppose correcting the import file might fix the problem automatically if that is what you want

**Comment by andrewvanbreda** [comment] 2016-10-03 13:08
Further notes on this for the other example you gave of dung and carrion.
It is not a broad biotope, it is listed as a resource instead, but as it doesn't have a parent it has been positioned at the top level of the broad biotopes/specific biotopes/resources list
Again I believe the importer has behaved correctly given the data, but the same comment applies that this may not be what you want

**Comment by johnvanbreda** [comment] 2016-10-11 10:28
@andrewvanbreda Thanks for your feedback, I think that the data as imported covers this structural change, so we are OK on that. You can assume this is sorted unless you hear otherwise.

@HDean Referring back to Jon's PowerPoint (Osiris and Isis report page.ppt) I've added the %rep to the hierarchical output (http://www.brc.ac.uk/pantheon/osiris/hierarchy?dynamic-sample_id=536592). The ppt also suggests adding the conservation status to the panels, but it won't fit realistically unless there are hardly any statuses. 
The document also describes that we should highlight the "sub-headings" differently and also the boxes which are used to "assign quality".  Can I have a definitive list of which are which please? I thought this information might be on your hierarchies document but I don't have a key to what the colours mean.

**Comment by HDean** [comment] 2016-10-12 18:06
On the hierarchy diagrams, any box that is outlined in a colour but is filled white is a subheading, That makes subheadings:

conifer or broadleaved
tree species
soil humidity
base status
woodland habitat
terrestrial aspect
flow
habitats

**Comment by HDean** [comment] 2016-10-12 18:16
Any that are using to assign quality have a superscript suffix of "QI" (QI = quality indicator), too many to list!
It might be further complicated by some habitats or resources being quality indicators within one biotope but the same habitat or resource not being a quality indicator in another biotope. I am certain which ones this might affect but I think "wet woodland" is an example - as a habitat under tree associated, it is not a QI but is when considered a resource under arboreal, but is a QI as a habitat under wetland!

**Comment by HDean** [comment] 2016-10-14 15:23
Hi @johnvanbreda,
I realised that in my Access database I have identified which traits are subheadings by adding an extra column into the traits table called "label" (not sure why I called it label!). I am not sure if this has been translated into Pantheon. Including subheadings is linked to #53 - these may not be included in future so I would not do too much work on this in case we remove them.

**Comment by HDean** [comment] 2016-10-25 14:42
Hi @johnvanbreda 
Following from discussions this morning, there are few issues with the Osiris reports that need ironing out:
1. PRIORITY - in the hierarchy report, the broad biotopes show % representation but the habitats and resources do not - can they be added?
2. PRIORITY - In the hierarchy report, the link to the species list from the number of species is not working. It opens the table but states that there is no information to show.
3. Where % representation is less than 1%, can it be shown as <1% - at present it shows as 1% or 0% (this goes for where ever % representation appears)
4. % representation on the tabular hierarchy report is incorrect (it is showing representation of the sample, not the species).

**Comment by HDean** [comment] 2016-10-26 10:43
Hi @johnvanbreda 
One more thing to add to the list!
1. Can you add the buttons at the bottom of page to the Osiris tabular report. They are present on the tabular hierarchy and hierarchy reports but have been missed on this one.
   Thanks.

**Comment by HDean** [comment] 2016-10-26 11:06
Sorry @johnvanbreda, there's more!
1. there is no conservation status in the Osiris tabular report. The column is there but the data is missing. The conservation status should be a list like "4NS, 5NR, 6 Legal Protection, 7 Priority Species, 2 Notable A" (Jon says that this was there before?). What would be great if there could be a link from this that lists the species and their conservation status.

I think there will be more coming but I am waiting for clarification from Jon. And I may set up another issue to cover it.

**Comment by HDean** [comment] 2016-10-26 12:23
Hi @johnvanbreda 
I also have another query which relates back to what Andy mentioned (on 3rd October) about plant-associated and dung & carrion traits and resources - are these showing up on the reporting at all? If so, how?

**Comment by johnvanbreda** [comment] 2016-10-28 18:06
Fixed - "% representation on the tabular hierarchy report is incorrect (it is showing representation of the sample, not the species)."
Fixed - "Can you add the buttons at the bottom of page to the Osiris tabular report. They are present on the tabular hierarchy and hierarchy reports but have been missed on this one. Thanks."

**Comment by johnvanbreda** [comment] 2016-10-31 15:07
Fixed - "there is no conservation status in the Osiris tabular report. The column is there but the data is missing. The conservation status should be a list like "4NS, 5NR, 6 Legal Protection, 7 Priority Species, 2 Notable A" (Jon says that this was there before?). What would be great if there could be a link from this that lists the species and their conservation status."
Can you add the suggestion about a link as a new issue please (I prefer smaller, easily tracked issues rather than catch-all issues).

**Comment by johnvanbreda** [comment] 2016-11-01 14:02
Fixed:
PRIORITY - in the hierarchy report, the broad biotopes show % representation but the habitats and resources do not - can they be added?
PRIORITY - In the hierarchy report, the link to the species list from the number of species is not working. It opens the table but states that there is no information to show.

**Comment by johnvanbreda** [comment] 2016-11-09 21:14
Think this is all covered apart from the dung & carrion issue which is covered elsewhere - can it be closed?

**Comment by HDean** [comment] 2016-11-11 17:02
Closing as remaining issues are covered elsewhere.

**Closed as completed by HDean** 2016-11-11 17:02 UTC
